### ISSUE TITLE
CreateQuestion() should not return a list of QuizCard

### ISSUE THREAD

**Issue by f-rakete** [SteAlb89/QuizGame#1]
https://github.com/stefanborcia/QuizGame/blob/76d812f3d877a6d66ffe8a1e560e419c888758cd/QuizGame/UI.cs#L19-L42

This method looks OK, but it really gathers only the information of one Quiz Card object. Recommend refactoring

**Comment by stefanborcia** [comment]
it is ok if i return CreateQuestion() ?

**Comment by f-rakete** [comment]
> it is ok if i return CreateQuestion() ?


it would make sense if you returned one QuizCard object
