### ISSUE TITLE
use relative paths

### ISSUE THREAD

**Issue by f-rakete** [SteAlb89/QuizGame#8]
https://github.com/stefanborcia/QuizGame/blob/76d812f3d877a6d66ffe8a1e560e419c888758cd/QuizGame/Program.cs#L11

If you use an absolute hardcoded path, it will not run on any other computer - read about relative paths and change accordingly

**Comment by stefanborcia** [comment]
i understand, but i am searching, and i don't find some clear information about,could you help me ?

**Comment by stefanborcia** [comment]
i found this : string path = System.IO.Path.Combine(AppDomain.CurrentDomain.BaseDirectory, @"..\..\..\Data\Orders\questionList.xml");
